@startuml
skinparam classAttributeIconSize 0
class AAUOC{
newLocation(l : Location) : void
newEvent(e : Event) : void
newPerson(p : Person) : void
informEvent(e : Event) : void
register(m : Member,e : Event) : void
}

class Location{
description : String
address : String
}

AAUOC o-- Location

class Event{
date : Date
description : String
assign(l : Location) : void
}

AAUOC o-- Event
Event -- Location

class Conference{
max_attendees : Integer
}

Event <|-- Conference
Conference -- BoardMeeting

class BoardMeeting

Event <|-- BoardMeeting


class Person{
name : String
}

AAUOC o-- Person

class Member{
e-mail : String
}

Person <|-- Member
Member -- Event

class BoardMember

Member <|-- BoardMember
BoardMember -- BoardMeeting

@enduml